--Usuario de prueba (no para acceso)
-- Tipos de Mision
INSERT INTO tipos_mision(nombre_tipo) VALUES ('Entrega'),('Inspeccion'),('Vigilancia')
-- Modelos de Dron
INSERT INTO modelos_dron(nombre_modelo,fabricante,capacidad_carga_kg,autonomia_minutos)
VALUES ('Gamma','Stella',5.2,120),('Crux','Stella',7.5,80),('Lyra','Stella',10,150),
	   ('Leo','Stella',3.5,360),
	   ('Basalt','Geo',5.5,80),('Granite','Geo',3.6,130),('Diorite','Geo',7.5,60),
	   ('Latite','Geo',5.5,80),
	   ('DJ1','Agra',4,100),('DJ2','Agra',5.5,85),('DJ3','Agra',7,60).('DJ4','Agra',10,60)
-- Drones
INSERT INTO drones(id_modelo,estado) VALUES (1,'Disponible'),(1,'Disponible'),(1,'En Mantenimiento'),
	(1,'Disponible'),
	(2,'Disponible'),(2,'Disponible'),(2,'En Mantenimiento'),(2,'Disponible'),
	(3,'Disponible'),(3,'Disponible'),(3,'En Mantenimiento'),(3,'Disponible'),
	(4,'Disponible'),(4,'Disponible'),(4,'En Mantenimiento'),(4,'Disponible'),
	(5,'Disponible'),(5,'Disponible'),(5,'En Mantenimiento'),(5,'Disponible'),
	(6,'Disponible'),(6,'Disponible'),(6,'En Mantenimiento'),(6,'Disponible'),
	(7,'Disponible'),(7,'Disponible'),(7,'En Mantenimiento'),(7,'Disponible'),
	(8,'Disponible'),(8,'Disponible'),(8,'En Mantenimiento'),(8,'Disponible'),
	(9,'Disponible'),(9,'Disponible'),(9,'En Mantenimiento'),(9,'Disponible'),
	(10,'Disponible'),(10,'Disponible'),(10,'En Mantenimiento'),(10,'Disponible'),
	(11,'Disponible'),(11,'Disponible'),(11,'En Mantenimiento'),(11,'Disponible'),
	(12,'Disponible'),(12,'Disponible'),(12,'En Mantenimiento'),(12,'Disponible')
-- Misiones de Drones sin uso en 30 dias
-- Misiones con drones que no se han usado en 30 dias (4,8,12,16......)
-- Tipos mision ('Entrega','Inspeccion',Vigilancia)
INSERT INTO misiones(id_dron_asignado,id_tipo_mision,id_operador_creador,fecha_creacion,
					fecha_inicio_planificada,fecha_fin_planificada,
					fecha_inicio_real, fecha_fin_real,
					estado,ruta) VALUES
					(4,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(8,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(12,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(16,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(20,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(24,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(28,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(32,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(38,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada'),
					(42,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Completada')
-- Misiones fallidas de ciertos drones
INSERT INTO misiones(id_dron_asignado,id_tipo_mision,id_operador_creador,fecha_creacion,
					fecha_inicio_planificada,fecha_fin_planificada,
					fecha_inicio_real, fecha_fin_real,
					estado,ruta) VALUES
					(2,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(2,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(9,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(9,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(9,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(9,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(9,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(14,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(21,2,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(34,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,3,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida'),
					(40,1,1,placeholder,placeholder,placeholder,placeholder,placeholder,
					'Fallida')




